package com.wlopera.cliente.cmf.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-10-30T23:15:21.620-05:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://cliente.wlopera.com/", name = "ClienteCMFServicio")
@XmlSeeAlso({ObjectFactory.class})
public interface ClienteCMFServicio {

    @WebMethod
    @RequestWrapper(localName = "getCMFPorAnnio", targetNamespace = "http://cliente.wlopera.com/", className = "com.wlopera.cliente.cmf.soap.GetCMFPorAnnio")
    @ResponseWrapper(localName = "getCMFPorAnnioResponse", targetNamespace = "http://cliente.wlopera.com/", className = "com.wlopera.cliente.cmf.soap.GetCMFPorAnnioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.wlopera.cliente.cmf.soap.Campeonato getCMFPorAnnio(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getListaCMFTodos", targetNamespace = "http://cliente.wlopera.com/", className = "com.wlopera.cliente.cmf.soap.GetListaCMFTodos")
    @ResponseWrapper(localName = "getListaCMFTodosResponse", targetNamespace = "http://cliente.wlopera.com/", className = "com.wlopera.cliente.cmf.soap.GetListaCMFTodosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.wlopera.cliente.cmf.soap.Campeonato> getListaCMFTodos();

    @WebMethod
    @RequestWrapper(localName = "getListaCMFPorCampeonatoGanado", targetNamespace = "http://cliente.wlopera.com/", className = "com.wlopera.cliente.cmf.soap.GetListaCMFPorCampeonatoGanado")
    @ResponseWrapper(localName = "getListaCMFPorCampeonatoGanadoResponse", targetNamespace = "http://cliente.wlopera.com/", className = "com.wlopera.cliente.cmf.soap.GetListaCMFPorCampeonatoGanadoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.wlopera.cliente.cmf.soap.Campeonato> getListaCMFPorCampeonatoGanado(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
