package com.wlopera.cliente.cmf.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-10-31T21:38:52.504-05:00
 * Generated source version: 3.2.2
 *
 */
@WebServiceClient(name = "ClienteCMFServicioService",
                  wsdlLocation = "file:src/main/java/resources/clientecmfservicio.wsdl",
                  targetNamespace = "http://cliente.wlopera.com/")
public class ClienteCMFServicioService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cliente.wlopera.com/", "ClienteCMFServicioService");
    public final static QName ClienteCMFServicioPort = new QName("http://cliente.wlopera.com/", "ClienteCMFServicioPort");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/java/resources/clientecmfservicio.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ClienteCMFServicioService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:src/main/java/resources/clientecmfservicio.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ClienteCMFServicioService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ClienteCMFServicioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClienteCMFServicioService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ClienteCMFServicioService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ClienteCMFServicioService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ClienteCMFServicioService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ClienteCMFServicio
     */
    @WebEndpoint(name = "ClienteCMFServicioPort")
    public ClienteCMFServicio getClienteCMFServicioPort() {
        return super.getPort(ClienteCMFServicioPort, ClienteCMFServicio.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteCMFServicio
     */
    @WebEndpoint(name = "ClienteCMFServicioPort")
    public ClienteCMFServicio getClienteCMFServicioPort(WebServiceFeature... features) {
        return super.getPort(ClienteCMFServicioPort, ClienteCMFServicio.class, features);
    }

}
